import { describe, expect, it } from "vitest";
import { reportToMarkdown, safeHttpUrl } from "@/core/report/markdown";
import { fixtureReport } from "./fixtures";

describe("reportToMarkdown", () => {
  const md = reportToMarkdown(fixtureReport());

  it("includes header metadata", () => {
    expect(md).toMatch(/^# DEV FIXTURE report/);
    expect(md).toContain("**Subject:** DEVTOKEN");
    expect(md).toContain("2026-01-01T12:00:00.000Z");
    expect(md).toContain("devprovider / dev-model-1");
    expect(md).toContain("Dev Market Feed, Dev DEX");
  });

  it("labels claims and cites evidence", () => {
    expect(md).toContain("- **[FACT]** DEVTOKEN trades at 1.23 USD. [E1]");
    expect(md).toContain("- **[INFERENCE]** Demand appears steady. [E1]");
    expect(md).toContain("- **[UNKNOWN]** Holder distribution is unknown.");
  });

  it("skips empty sections and lists open questions", () => {
    expect(md).toContain("## Market");
    expect(md).not.toContain("## Narrative");
    expect(md).toContain("## Open questions\n\n- Who are the largest holders?");
  });

  it("lists sources with only http(s) urls", () => {
    expect(md).toContain("## Sources");
    expect(md).toContain("**[E1]** `get_market_data`");
    expect(md).toContain("Dev Market Feed (devfeed): <https://example.com/market>");
    expect(md).toContain("Dev DEX (devdex)");
    expect(md).not.toContain("javascript:");
  });

  it("ends with the disclaimer footer", () => {
    expect(md.trim().endsWith("Generated by ROVANTA. Not investment advice.")).toBe(true);
  });

  it("notes fallback and downgraded claims", () => {
    const base = fixtureReport();
    const out = reportToMarkdown({
      ...base,
      fallback: true,
      sections: {
        ...base.sections,
        risks: { summary: "", claims: [{ text: "r", kind: "INFERENCE", evidenceIds: [], downgraded: true }] },
      },
    });
    expect(out).toContain("Fallback report");
    expect(out).toContain("- **[INFERENCE]** r _(labelled inference: no supporting evidence cited)_");
  });
});

describe("safeHttpUrl", () => {
  it("accepts only absolute http(s) urls", () => {
    expect(safeHttpUrl("https://example.com/a")).toBe("https://example.com/a");
    expect(safeHttpUrl("http://example.com")).toBe("http://example.com/");
    expect(safeHttpUrl("javascript:alert(1)")).toBeNull();
    expect(safeHttpUrl("data:text/html,x")).toBeNull();
    expect(safeHttpUrl("/relative")).toBeNull();
    expect(safeHttpUrl(undefined)).toBeNull();
  });
});
