import { SECTION_KEYS, SECTION_TITLES, type Claim, type ResearchReport } from "./schema";

/** Returns the normalized URL only when it is an absolute http(s) URL. */
export function safeHttpUrl(url: string | undefined | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url.trim());
    return parsed.protocol === "http:" || parsed.protocol === "https:" ? parsed.href : null;
  } catch {
    return null;
  }
}

function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function claimLine(claim: Claim): string {
  const refs = claim.evidenceIds.map((id) => `[${oneLine(id)}]`).join(" ");
  const note = claim.downgraded ? " _(labelled inference: no supporting evidence cited)_" : "";
  return `- **[${claim.kind}]** ${oneLine(claim.text)}${refs ? ` ${refs}` : ""}${note}`;
}

export function reportToMarkdown(report: ResearchReport): string {
  const lines: string[] = [];
  lines.push(`# ${oneLine(report.title)}`, "");
  lines.push(`**Subject:** ${oneLine(report.subject)}`, "");
  lines.push(`- **Generated:** ${report.generatedAt}`);
  lines.push(`- **Model:** ${oneLine(report.model.provider)} / ${oneLine(report.model.model)}`);
  lines.push(
    `- **Data sources:** ${report.dataSources.length ? report.dataSources.map(oneLine).join(", ") : "none"}`,
  );
  lines.push(`- **Evidence items:** ${report.evidence.length}`, "");
  if (report.fallback) {
    lines.push("> Fallback report: model output could not be parsed. Content is assembled from evidence only.", "");
  }
  lines.push(
    "_Labels: FACT = supported by cited evidence; INFERENCE = analysis, may be wrong; UNKNOWN = insufficient data._",
    "",
  );

  for (const key of SECTION_KEYS) {
    const section = report.sections[key];
    const summary = section.summary.trim();
    if (!summary && section.claims.length === 0) continue;
    lines.push(`## ${SECTION_TITLES[key]}`, "");
    if (summary) lines.push(summary, "");
    if (section.claims.length) lines.push(...section.claims.map(claimLine), "");
  }

  if (report.openQuestions.length) {
    lines.push("## Open questions", "");
    lines.push(...report.openQuestions.map((q) => `- ${oneLine(q)}`), "");
  }

  if (report.evidence.length) {
    lines.push("## Sources", "");
    for (const item of report.evidence) {
      lines.push(`- **[${oneLine(item.id)}]** \`${oneLine(item.tool)}\` — ${oneLine(item.summary)} (fetched ${item.fetchedAt})`);
      for (const source of item.sources) {
        const url = safeHttpUrl(source.url);
        lines.push(`  - ${oneLine(source.name)} (${oneLine(source.provider)})${url ? `: <${url}>` : ""}`);
      }
    }
    lines.push("");
  }

  lines.push("---", "", "Generated by ROVANTA. Not investment advice.", "");
  return lines.join("\n");
}
